### ISSUE TITLE
I want to be able to freely change the memory allocation

### ISSUE THREAD

**Issue by ghost** [microsoft/WSA#217]
### Is your feature request related to a problem? Please describe

Memory is now automatically allocated

### Describe the solution you'd like

Make memory allocation flexible

### Please specify the version of Windows Subsystem for Android

v2211.40000.7.0

**Comment by nieubank** [comment]
This is on our radar for a future release.

**Comment by nieubank** [comment]
Resolved in an upcoming release.

**Comment by admin-elvistrujanovic** [comment]
Well, this thing doesn't work for me - even if I installed prerelease version - I even tried nightly version but the behavior is still the same. Memory allocation settings I can choose the option or write custom RAM allocation but Apply button is greyed out and not clickable. And none of settings I choose there doesn't apply - it always restarts to the default allocation. Is this thing work or I need to be approved by Microsoft to use those prerelease (release preview) features and not just install the preview version of the app, but to be registered by servers on Microsoft that I'm a tester.

**Comment by nieubank** [comment]
> 

If the "Custom" option is available in the Memory and performance section of Advanced settings, the feature should be available to you. How much RAM does your Windows machine have and how much are you trying to allocate to Android?

There should be a subtext indicating what values are available to you and entering a value between those should enable the Apply button.

**Comment by admin-elvistrujanovic** [comment]
> > 
> 
> If the "Custom" option is available in the Memory and performance section of Advanced settings, the feature should be available to you. How much RAM does your Windows machine have and how much are you trying to allocate to Android?
> 
> There should be a subtext indicating what values are available to you and entering a value between those should enable the Apply button.

Well, I've tried that already but anything I type (including the number thay shows to me that can be used in my laptop), the apply button is still unable to work and it's still unclickable


All other options (RAM profiles) except default RAM profile it cannot apply so that feature is kindla unavailable for me in that way how it works or better to stay, doesn't work for me.
